import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const wasmPkgDir = path.join(process.cwd(), 'graph-analysis-wasm', 'pkg');
const wasmJsPath = path.join(wasmPkgDir, 'graph_analysis_wasm.js');
const wasmBinaryPath = path.join(wasmPkgDir, 'graph_analysis_wasm_bg.wasm');

function assertWasmBuildArtifacts() {
  if (!fs.existsSync(wasmJsPath) || !fs.existsSync(wasmBinaryPath)) {
    const message = `WASM build artifacts missing under ${wasmPkgDir}. Run "npm run build-wasm" first.`;
    if (prod) {
      console.error(`❌ ${message}`);
      process.exit(1);
    }
    throw new Error(message);
  }
}

// Inject wasm-bindgen glue into main.ts (binary is bundled via src/wasm/embedded.ts + loader binary)
const injectWasmCode = {
  name: 'inject-wasm-code',
  setup(build) {
    build.onLoad({ filter: /src\/main\.ts$/ }, async (args) => {
      assertWasmBuildArtifacts();
      const source = await fs.promises.readFile(args.path, 'utf8');
      const wasmJsCode = await fs.promises.readFile(wasmJsPath, 'utf8');

      // Create a modified version of the WASM JS code that works with CommonJS
      const modifiedWasmJsCode = wasmJsCode
        .replace('export default __wbg_init;', '')
        .replace(/export\s*{\s*initSync\s*,\s*__wbg_init\s+as\s+default\s*};?/g, '') // Remove combined export with default
        .replace(/export\s*{\s*__wbg_init\s+as\s+default\s*};?/g, '') // Remove default export only
        .replace('export { initSync };', '')
        .replace(/export function ([a-zA-Z_]+)/g, 'function $1')
        .replace(/export async function ([a-zA-Z_]+)/g, 'async function $1')
        // Remove import.meta usage
        .replace(/new URL\([^)]+\)/g, 'undefined')
        // Obsidian bundle always passes Uint8Array; drop wasm-bindgen URL fetch (scanner + no network for WASM)
        .replace(/module_or_path = fetch\(module_or_path\);/, 'module_or_path = Promise.reject(new Error("WASM must be embedded bytes"));');

      const modifiedSource = `
// Injected wasm-bindgen glue (WASM bytes imported from src/wasm/embedded.ts)
${modifiedWasmJsCode}

// Original TypeScript code
${source}`;

      return {
        contents: modifiedSource,
        loader: 'ts',
      };
    });
  },
};


// Path alias resolver plugin
const pathAliasPlugin = {
  name: 'path-alias',
  setup(build) {
    // Resolve path aliases
    build.onResolve({ filter: /^@\// }, (args) => {
      const aliasPath = args.path.replace(/^@\//, '');
      const resolvedPath = path.join(rootDir, 'src', aliasPath);
      return {
        path: resolvedPath,
        namespace: 'file',
      };
    });
  },
};

// Copy CSS file to the correct location for Obsidian
const copyCssFile = {
  name: 'copy-css-file',
  setup(build) {
    build.onEnd(() => {
      const outputDir = path.join(process.cwd(), 'dist');
      const cssSourcePath = path.join(outputDir, 'styles', 'styles.css');
      const cssTargetPath = path.join(outputDir, 'styles.css');
      
      try {
        // Check if the source CSS file exists (from the entry point)
        if (fs.existsSync(cssSourcePath)) {
          fs.copyFileSync(cssSourcePath, cssTargetPath);
          console.log(`✅ Copied CSS from ${cssSourcePath} to ${cssTargetPath}`);
        } else {
          // Fallback: check if main.css exists (from CSS import in main.ts)
          const mainCssPath = path.join(outputDir, 'main.css');
          if (fs.existsSync(mainCssPath)) {
            fs.copyFileSync(mainCssPath, cssTargetPath);
            console.log(`✅ Copied CSS from ${mainCssPath} to ${cssTargetPath}`);
          } else {
            console.warn(`⚠️  CSS file not found. Expected at ${cssSourcePath} or ${mainCssPath}`);
          }
        }
      } catch (error) {
        console.error(`❌ Error copying CSS file: ${error.message}`);
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts", "src/styles/styles.css"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: "dist",
  loader: {
    ".wasm": "binary",
  },
  plugins: [pathAliasPlugin, injectWasmCode, copyCssFile],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
} 