import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Copy WASM files to the output directory
const copyWasmFiles = {
  name: 'copy-wasm-files',
  setup(build) {
    build.onEnd(() => {
      const wasmDir = path.join(process.cwd(), 'graph-analysis-wasm', 'pkg');
      const outputDir = path.join(process.cwd(), 'dist');
      
      // Create the output directory if it doesn't exist
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }
      
      // Copy the WASM file
      const wasmFile = path.join(wasmDir, 'graph_analysis_wasm_bg.wasm');
      const outputWasmFile = path.join(outputDir, 'graph_analysis_wasm_bg.wasm');
      
      try {
        if (fs.existsSync(wasmFile)) {
          fs.copyFileSync(wasmFile, outputWasmFile);
          console.log(`Copied ${wasmFile} to ${outputWasmFile}`);
        } else {
          console.error(`WASM file not found at ${wasmFile}`);
        }
      } catch (error) {
        console.error(`Error copying WASM file: ${error.message}`);
      }
    });
  },
};

// Inject WASM JavaScript code into the main.js file
const injectWasmCode = {
  name: 'inject-wasm-code',
  setup(build) {
    build.onLoad({ filter: /src\/main\.ts$/ }, async (args) => {
      const source = await fs.promises.readFile(args.path, 'utf8');
      const wasmJsPath = path.join(process.cwd(), 'graph-analysis-wasm', 'pkg', 'graph_analysis_wasm.js');
      const wasmJsCode = await fs.promises.readFile(wasmJsPath, 'utf8');
      
      // Create a modified version of the WASM JS code that works with CommonJS
      const modifiedWasmJsCode = wasmJsCode
        .replace('export default __wbg_init;', '')
        .replace('export { initSync };', '')
        .replace(/export function ([a-zA-Z_]+)/g, 'function $1')
        .replace(/export async function ([a-zA-Z_]+)/g, 'async function $1')
        // Remove import.meta usage
        .replace(/new URL\([^)]+\)/g, 'undefined');
      
      // Inject the WASM JS code at the top of the file
      const modifiedSource = `
// Injected WASM module code
${modifiedWasmJsCode}

// Original TypeScript code
${source}`;
      
      return {
        contents: modifiedSource,
        loader: 'ts',
      };
    });
  },
};


const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts", "src/styles.css"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: "dist",
  plugins: [injectWasmCode, copyWasmFiles],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
} 