import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Copy WASM files to the output directory
const copyWasmFiles = {
  name: 'copy-wasm-files',
  setup(build) {
    build.onEnd(() => {
      const wasmDir = path.join(process.cwd(), 'graph-analysis-wasm', 'pkg');
      const outputDir = path.join(process.cwd(), 'dist');
      
      // Create the output directory if it doesn't exist
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }
      
      // Copy the WASM file
      const wasmFile = path.join(wasmDir, 'graph_analysis_wasm_bg.wasm');
      const outputWasmFile = path.join(outputDir, 'graph_analysis_wasm_bg.wasm');
      
      try {
        if (fs.existsSync(wasmFile)) {
          fs.copyFileSync(wasmFile, outputWasmFile);
          console.log(`Copied ${wasmFile} to ${outputWasmFile}`);
        } else {
          console.error(`WASM file not found at ${wasmFile}`);
        }
      } catch (error) {
        console.error(`Error copying WASM file: ${error.message}`);
      }
    });
  },
};

// Copy knowledge domains template file to the output directory
const copyKnowledgeDomainsTemplate = {
  name: 'copy-knowledge-domains-template',
  setup(build) {
    build.onEnd(() => {
      const sourceFile = path.join(process.cwd(), 'src', 'ai', 'knowledge-domains.json');
      const outputDir = path.join(process.cwd(), 'dist');
      const targetFile = path.join(outputDir, 'knowledge-domains.json');
      
      // Create the output directory if it doesn't exist
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }
      
      try {
        if (fs.existsSync(sourceFile)) {
          // Verify the source file is valid JSON before copying
          try {
            const sourceContent = fs.readFileSync(sourceFile, 'utf8');
            JSON.parse(sourceContent); // Just to validate, we don't need the result
            
            // Copy the file to the target location
            fs.copyFileSync(sourceFile, targetFile);
            console.log(`✅ Successfully copied knowledge domains template from ${sourceFile} to ${targetFile}`);
          } catch (jsonError) {
            console.error(`❌ ERROR: Knowledge domains template JSON is invalid: ${jsonError.message}`);
            console.error('Build will continue but the plugin may not function correctly without a valid knowledge domains template');
          }
        } else {
          console.error(`❌ CRITICAL ERROR: Knowledge domains template file not found at ${sourceFile}`);
          console.error('This file is required for the plugin to function correctly');
          
          // Make the build fail if in production mode
          if (prod) {
            process.exit(1);
          }
        }
      } catch (error) {
        console.error(`❌ Error handling knowledge domains template: ${error.message}`);
        
        // Make the build fail if in production mode
        if (prod) {
          process.exit(1);
        }
      }
    });
  },
};

// Inject WASM JavaScript code and embed WASM binary as base64 into the main.js file
const injectWasmCode = {
  name: 'inject-wasm-code',
  setup(build) {
    build.onLoad({ filter: /src\/main\.ts$/ }, async (args) => {
      const source = await fs.promises.readFile(args.path, 'utf8');
      const wasmJsPath = path.join(process.cwd(), 'graph-analysis-wasm', 'pkg', 'graph_analysis_wasm.js');
      const wasmJsCode = await fs.promises.readFile(wasmJsPath, 'utf8');
      const wasmFilePath = path.join(process.cwd(), 'graph-analysis-wasm', 'pkg', 'graph_analysis_wasm_bg.wasm');

      // Read and base64-encode the WASM binary for embedding (avoids requestUrl file:// protocol issues)
      let wasmBase64 = '';
      if (fs.existsSync(wasmFilePath)) {
        const wasmBinary = fs.readFileSync(wasmFilePath);
        wasmBase64 = wasmBinary.toString('base64');
      } else {
        console.warn(`WASM file not found at ${wasmFilePath}, plugin may fail to load`);
      }

      // Create a modified version of the WASM JS code that works with CommonJS
      const modifiedWasmJsCode = wasmJsCode
        .replace('export default __wbg_init;', '')
        .replace(/export\s*{\s*initSync\s*,\s*__wbg_init\s+as\s+default\s*};?/g, '') // Remove combined export with default
        .replace(/export\s*{\s*__wbg_init\s+as\s+default\s*};?/g, '') // Remove default export only
        .replace('export { initSync };', '')
        .replace(/export function ([a-zA-Z_]+)/g, 'function $1')
        .replace(/export async function ([a-zA-Z_]+)/g, 'async function $1')
        // Remove import.meta usage
        .replace(/new URL\([^)]+\)/g, 'undefined');

      // Inject the WASM JS code and embedded WASM base64 at the top of the file
      const modifiedSource = `
// Injected WASM module code
${modifiedWasmJsCode}

// Embedded WASM binary (base64) - avoids requestUrl file:// protocol issues in Obsidian
const EMBEDDED_WASM_BASE64 = ${JSON.stringify(wasmBase64)};

// Original TypeScript code
${source}`;

      return {
        contents: modifiedSource,
        loader: 'ts',
      };
    });
  },
};


// Path alias resolver plugin
const pathAliasPlugin = {
  name: 'path-alias',
  setup(build) {
    // Resolve path aliases
    build.onResolve({ filter: /^@\// }, (args) => {
      const aliasPath = args.path.replace(/^@\//, '');
      const resolvedPath = path.join(rootDir, 'src', aliasPath);
      return {
        path: resolvedPath,
        namespace: 'file',
      };
    });
  },
};

// Copy CSS file to the correct location for Obsidian
const copyCssFile = {
  name: 'copy-css-file',
  setup(build) {
    build.onEnd(() => {
      const outputDir = path.join(process.cwd(), 'dist');
      const cssSourcePath = path.join(outputDir, 'styles', 'styles.css');
      const cssTargetPath = path.join(outputDir, 'styles.css');
      
      try {
        // Check if the source CSS file exists (from the entry point)
        if (fs.existsSync(cssSourcePath)) {
          fs.copyFileSync(cssSourcePath, cssTargetPath);
          console.log(`✅ Copied CSS from ${cssSourcePath} to ${cssTargetPath}`);
        } else {
          // Fallback: check if main.css exists (from CSS import in main.ts)
          const mainCssPath = path.join(outputDir, 'main.css');
          if (fs.existsSync(mainCssPath)) {
            fs.copyFileSync(mainCssPath, cssTargetPath);
            console.log(`✅ Copied CSS from ${mainCssPath} to ${cssTargetPath}`);
          } else {
            console.warn(`⚠️  CSS file not found. Expected at ${cssSourcePath} or ${mainCssPath}`);
          }
        }
      } catch (error) {
        console.error(`❌ Error copying CSS file: ${error.message}`);
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts", "src/styles/styles.css"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: "dist",
  plugins: [pathAliasPlugin, injectWasmCode, copyWasmFiles, copyKnowledgeDomainsTemplate, copyCssFile],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
} 